### PR TITLE
Changed the engines properties to protected and made certain methods …

### PR DESCRIPTION
**Pull request by caroen**

### CODE REVIEW

**Comment by davidebbo** [comment]
Not sure I like blindly making everything protected without a scenario in mind, as that can make it harder to avoid breaking changes later. Can you limit the extensibility to what you concretely need now? Also, if you need to expose a field, please change it to an automatic property (with private setting for readonly).

**Comment by caroen** [comment]
by "automatic property (with private setting for readonly).", do you mean something like this?

```
private readonly SomeClass _myPoperty;
public SomeClass MyPoperty { get { return _myProperty; }}
```

**Comment by davidebbo** [comment]
Right, the second one using `{ get; private set; }`.

**Comment by davidebbo** [comment]
Are you still hoping to get this in, with the suggested change? Thanks.

**Comment by caroen** [comment]
Sorry for the delay, I reverted the previous changes and only kept the following changes:
* **IsPhysicalFileNewer** as protected virtual
* **BaseVirtualPath** as protected, with private setter
* **AssemblyLastWriteTime** as protected, with private setter

**Comment by davidebbo** [comment]
It's in 2.3.6, thanks!

**Comment by caroen** [comment]
awesome :)

**Pull request closed without merging**
