### PR TITLE
Adding fix to normalize virtual paths to match format stored in preco…

### PR DESCRIPTION
**Pull request by TheCodeKing**
…mpiled lookups - see 2f62149ace983e2201b008758110796a7980c5a5

This is the same fix that was applied to PrecompiledMvcEngine, and resolves an issue with path lookups from applications such as Sitecore.

### CODE REVIEW

**Comment by davidebbo** [comment]
Looks good, but would be good to share `EnsureVirtualPathPrefix` with `PrecompiledMvcEngine` to avoid duplication.

**Comment by TheCodeKing** [comment]
Added a fix to keep things DRY.

**Comment by TheCodeKing** [comment]
Any chance of merging this in and releasing? Looking to use this on a live project :)

**Comment by davidebbo** [comment]
Squashed and pushed. There is another PR pending, so I'll wait for that to make a release. Ping me in a couple days if it hasn't happened :)

**Comment by TheCodeKing** [comment]
Great thanks!

**Comment by davidebbo** [comment]
Ok, it's in 2.3.5.

**Pull request closed without merging**
