### PR TITLE
Added support of VS2019 in VSIX

### PR DESCRIPTION
**Pull request by Daddoon**
- Changed the source.extension.vsixmanifest
- Updated README.md

### CODE REVIEW

**Comment by Daddoon** [comment]
- I was **unable** to build the project from **VS2017 / VS2019**
- I was **able** to build the project from **VS2015**

I don't know if it is related to my machine, but some attributes were not available on my VS2017 / VS2019 installation, about VisualStudio.Interop.Shell namespace, even if i have installed the Visual Studio Extension tools on both. But no issue with VS2015 with the updated manifest for building the **VSIX**.

- I have installed on VS2019 Preview. Installation **OK**.
- The only test i have made is to open a new CSHTML file i was needing for an old corporate project that was unable to generate the Razor Generated file (because of VS2019 extension missing). I juste opened the file with the newly installed plugin, Saved the file and my code behind file was generated successfully ! 

Just don't forget to add **RazorGenerator** on your file CustomTool property of course !

It seem ok to me !

I have published a VSIX installer on my Forked repo if needed. But i may have forgotten to update the version number of the plugin when installed in Visual Studio.

**Comment by Jehoel** [comment]
Thank you. Sounds good.

I'll try (but cannot commit) to reviewing everything else is okay - I need to get my VS2015 installation rebuilt for RazorGenerator anyway. More realistically I might be able to get this merged around the 18th-19th - just to warn you.

**Comment by Daddoon** [comment]
Thanks Jehoel. No problem, i will stick to my build for the moment, and i will reinstall the official VSIX afterward when it will be published by the official repo

**Comment by Jehoel** [comment]
That was weird - after rebuilding from within VS2015 and reopening the VSIX it now recognizes my VS2019 install. I'll put that down to a glitch in VS2019 rather than this extension.

I'll increment the package version and merge this now.

I can't publish this extension to the Marketplace without my MSA account being added to this project's Marketplace Publisher entry. I'll contact the other maintainers now.

**Comment by Daddoon** [comment]
Thanks for the merge @Jehoel !
For info, my build is still working on Preview 2.

**Comment by davidebbo** [comment]
I responded to @Jehoel offline on getting him publisher access to the marketplace.

**Comment by Daddoon** [comment]
Thanks for the feedback @davidebbo .

If you or @Jehoel can confirm when the extension will be available on the gallery would be cool for me, as i would be able to uninstall my own build and install the extension from the Marketplace gallery instead.

**Comment by Jehoel** [comment]
I replied to @davidebbo’s email on Monday with the necessary details. I was busy over the weekend, unfortunately. I also emailed Pranav on Monday with my details for adding me to NuGet.

Things move slowly with unpaid projects :)

**Comment by davidebbo** [comment]
I've given you access in the VS Gallery. I can give you NuGet access as well. Is your id there 'Jehoel'?

**Pull request merged**
