### PR TITLE
Use "Func<boo>" instead of bool as the engine property's return type to avoid issues about null of HttpContext when it used.

### PR DESCRIPTION
**Pull request by kissstudio**
When create the engine from Applciation_Start and used HttpContext to
set engine's property for some reason we'll get exception about null of
HttpContext, and use "Func<boo>" instead of bool as the engine property's
return type will avoid the issue.

### CODE REVIEW

**Comment by pranavkm** [comment]
@kissstudio - could you elaborate on what your scenario for doing this is?

**Comment by davidebbo** [comment]
Isn't that a breaking change?

**Comment by pranavkm** [comment]
Yup, it would be. Unless there's a super pertinent reason I don't think we should take it.

**Comment by kissstudio** [comment]
`protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();

            WebApiConfig.Register(GlobalConfiguration.Configuration);
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);

            ViewEngineConfig.RegisterPrecompiledMvcEngine();
        }`

` public static void RegisterPrecompiledMvcEngine()
    {
        var engine = new PrecompiledMvcEngine(typeof(ViewEngineConfig).Assembly)
        {
            UsePhysicalViewsIfNewer = UsePhysicalViewsIfNewer,
            //PreemptPhysicalFiles = PreemptPhysicalFiles
        };

        ViewEngines.Engines.Insert(0, engine);

        // StartPage lookups are done by WebPages. 
        VirtualPathFactoryManager.RegisterVirtualPathFactory(engine);
    }

    public static bool UsePhysicalViewsIfNewer()
    {
        return HttpContext.Current.Request.IsLocal;
    }`

well, I want use HttpContext.Current.Request.IsLocal as the value of UsePhysicalViewsIfNewer 

instead of a fixed value

**Comment by pranavkm** [comment]
Are you able to initialize the view engine as part of `Begin_Request`?

**Comment by kissstudio** [comment]
I reserve my opinion on where and how to config the view engine.

**Pull request closed without merging**
