### PR TITLE
Convert RazorGenerator.Templating to PCL

### PR DESCRIPTION
**Pull request by nigel-sampson**
I've had some success using RazorGenerator as a way to build rich HTML for an embedded web view in WinRT projects (displaying Markdown for instance). This required RazorGenerator to be a PCL.

### CODE REVIEW

**Comment by davidebbo** [comment]
So I'm rather PCL clueless. This should have no noticeable effects on existing scenarios, right?

**Comment by nigel-sampson** [comment]
This shouldn't have any effect on existing scenarios, all it does is allow non .NET 4.0 projects to reference RazorGenerator.Templating.

**Comment by pranavkm** [comment]
:shipit:

**Comment by davidebbo** [comment]
It's in 2.3.3, thanks!

**Pull request merged**
